### ISSUE TITLE
How to load model and predict 1 image?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [pavanvyn/Galaxy-classification#2]
So sorry. Do you use the model trained and predict with 1 image? Can you tell me how to do it?

**Comment by pavanvyn** [comment]
Hi,
You need to use different sets for training and testing. Or use the k-fold cross-validation technique - (k-1)/k fraction of data for testing, and 1/k fraction of data for training - and repeat the same by shuffling the dataset. I, unfortunately, have not implemented this.
Hope this helps.
